# Generated by Django 4.0.4 on 2022-06-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jobmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='working_hours',
            new_name='working_hours_per_week',
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='currency',
            field=models.CharField(choices=[('rupee', 'Rs/-'), ('dollar', '$'), ('euro', '€')], default='$', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='jobtype',
            field=models.CharField(choices=[('part-time', 'Part-Time'), ('internship', 'Internship'), ('full-time', 'Full-Time')], default='full-time', max_length=255),
        ),
    ]
