# Generated by Django 4.0.4 on 2022-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_working_hours_jobmodel_working_hours_per_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='currency',
            field=models.CharField(choices=[('dollar', '$'), ('euro', '€'), ('rupee', 'Rs/-')], default='$', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='jobtype',
            field=models.CharField(choices=[('internship', 'Internship'), ('full-time', 'Full-Time'), ('part-time', 'Part-Time')], default='full-time', max_length=255),
        ),
    ]
