# Generated by Django 4.0.4 on 2022-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_jobmodel_currency_alter_jobmodel_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobmodel',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='currency',
            field=models.CharField(choices=[('rupee', 'Rs/-'), ('euro', '€'), ('dollar', '$')], default='$', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='jobtype',
            field=models.CharField(choices=[('part-time', 'Part-Time'), ('internship', 'Internship'), ('full-time', 'Full-Time')], default='full-time', max_length=255),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='salarytype',
            field=models.CharField(choices=[('per month', 'Per month'), ('per year', 'Per year')], default='per year', max_length=255),
        ),
    ]
